[package]
name = "bigame-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync"] }
zbus.workspace = true
serde.workspace = true
serde_json.workspace = true
libc.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bigame-core = { path = "../bigame-core" }
