//! Diagnostics: one page to hand to support, and the network measurements.
//!
//! Two things live here because they answer the same question from different
//! angles — "what is this machine doing?" — and because both are read-only.
//! Nothing on this page changes the system.
//!
//! The report is generated by `bigame_core::diagnostics`, which strips personal
//! identifiers as it builds rather than filtering afterwards. The page never
//! sees an unredacted version, so there is nothing here that could leak one.

use adw::prelude::*;
use gtk4::{gio, glib};
use libadwaita as adw;

use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;

use bigame_core::network::{self, Resolver};

use crate::i18n::i18n;
use crate::widgets::toast;

/// Resolvers offered for comparison, alongside whatever the system uses.
const PUBLIC_RESOLVERS: &[(&str, &str)] = &[
    ("Cloudflare", "1.1.1.1"),
    ("Google", "8.8.8.8"),
    ("Quad9", "9.9.9.9"),
    ("OpenDNS", "208.67.222.222"),
];

/// Domains queried by the DNS benchmark.
///
/// Distinct names on purpose: querying one repeatedly measures the resolver's
/// cache rather than the resolver, and a cold lookup is what a game launcher
/// actually performs.
const PROBE_DOMAINS: &[&str] = &[
    "steamcommunity.com",
    "store.steampowered.com",
    "epicgames.com",
    "gog.com",
    "ea.com",
    "ubisoft.com",
    "battle.net",
    "riotgames.com",
    "playstation.com",
    "xbox.com",
    "nvidia.com",
    "amd.com",
];

/// Build the Diagnostics page.
#[must_use]
pub fn build() -> gtk4::Widget {
    let page = adw::PreferencesPage::new();
    page.add(&network_group());
    page.add(&report_group());
    page.upcast()
}

// ── Network ─────────────────────────────────────────────────────────────────

/// Building a widget tree is inherently linear — splitting it yields helpers
/// with a single caller and no independent meaning — so the length lint is
/// allowed here rather than worked around.
#[allow(clippy::too_many_lines)]
fn network_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Network"));
    group.set_description(Some(&i18n(
        "Measured on the connection that carries your traffic, not on every \
         interface this machine happens to have.",
    )));

    let link_row = adw::ActionRow::builder()
        .title(i18n("Connection"))
        .subtitle(i18n("Checking…"))
        .build();
    group.add(&link_row);

    let qdisc_row = adw::ActionRow::builder()
        .title(i18n("Queue discipline"))
        .subtitle(i18n("Checking…"))
        .build();
    group.add(&qdisc_row);

    // Populated once, off the main thread; nothing here changes while the page
    // is open, so there is no reason to poll it.
    {
        let link_row = link_row.clone();
        let qdisc_row = qdisc_row.clone();
        glib::spawn_future_local(async move {
            let link = gio::spawn_blocking(network::primary_link)
                .await
                .ok()
                .flatten();
            if let Some(link) = link {
                link_row.set_title(&link.name);
                link_row.set_subtitle(&format!(
                    "{} · {} · MTU {}",
                    match link.medium {
                        network::Medium::Ethernet => i18n("Wired"),
                        network::Medium::WiFi => i18n("Wi-Fi"),
                        network::Medium::Virtual => i18n("Virtual"),
                        network::Medium::Unknown => i18n("Unknown"),
                    },
                    link.speed_mbps
                        .map_or_else(|| i18n("unknown speed"), |s| format!("{s} Mb/s")),
                    link.mtu.map_or_else(|| "?".to_owned(), |m| m.to_string())
                ));

                let modern = link.has_modern_qdisc();
                qdisc_row.set_subtitle(&format!(
                    "{} — {}",
                    link.qdisc.as_deref().unwrap_or(&i18n("unknown")),
                    if modern {
                        // Saying "already good" matters: offering to enable
                        // something that is on would be a no-op reported as
                        // an improvement.
                        i18n("already manages latency under load; nothing to change")
                    } else {
                        i18n("does not actively manage latency under load")
                    }
                ));
                qdisc_row.add_prefix(&status_icon(modern));
            } else {
                link_row.set_subtitle(&i18n("No default route — this machine is offline"));
                qdisc_row.set_visible(false);
            }
        });
    }

    // ── DNS benchmark ───────────────────────────────────────────────────
    let dns_group = adw::ExpanderRow::builder()
        .title(i18n("DNS resolver comparison"))
        .subtitle(i18n(
            "Measures how quickly each resolver answers a lookup. It does not \
             change the round-trip time of match traffic.",
        ))
        .build();

    let run_button = gtk4::Button::builder()
        .label(i18n("Measure"))
        .valign(gtk4::Align::Center)
        .css_classes(["suggested-action"])
        .build();
    dns_group.add_suffix(&run_button);
    group.add(&dns_group);

    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    {
        let dns_group = dns_group.clone();
        let rows = Rc::clone(&rows);
        let run_button = run_button.clone();
        run_button.clone().connect_clicked(move |_| {
            for row in rows.borrow_mut().drain(..) {
                dns_group.remove(&row);
            }
            run_button.set_sensitive(false);
            run_button.set_label(&i18n("Measuring…"));
            dns_group.set_expanded(true);

            let dns_group = dns_group.clone();
            let rows = Rc::clone(&rows);
            let run_button = run_button.clone();
            glib::spawn_future_local(async move {
                let results = gio::spawn_blocking(run_dns_benchmark)
                    .await
                    .unwrap_or_default();

                let fastest = network::fastest(&results).map(|r| r.resolver.name.clone());
                for result in &results {
                    let row = adw::ActionRow::builder()
                        .title(&result.resolver.name)
                        .build();
                    match &result.stats {
                        Some(stats) => {
                            row.set_subtitle(&format!(
                                "{} {:.1} ms · {} {:.1} ms · {} {:.1} ms",
                                i18n("median"),
                                stats.median_ms,
                                i18n("95th percentile"),
                                stats.p95_ms,
                                i18n("jitter"),
                                stats.jitter_ms
                            ));
                            if fastest.as_deref() == Some(result.resolver.name.as_str()) {
                                let badge = gtk4::Label::new(Some(&i18n("Fastest lookups")));
                                badge.add_css_class("caption");
                                badge.add_css_class("success");
                                badge.set_valign(gtk4::Align::Center);
                                row.add_suffix(&badge);
                            }
                        }
                        None => row.set_subtitle(&i18n("No response")),
                    }
                    dns_group.add_row(&row);
                    rows.borrow_mut().push(row);
                }

                // The disclaimer is part of the result, not a footnote: the
                // whole point is that a faster resolver is not a faster game.
                let note = adw::ActionRow::builder()
                    .title(i18n("What this does not mean"))
                    .subtitle(network::dns_disclaimer())
                    .build();
                note.add_prefix(&gtk4::Image::from_icon_name("dialog-information-symbolic"));
                dns_group.add_row(&note);
                rows.borrow_mut().push(note);

                run_button.set_sensitive(true);
                run_button.set_label(&i18n("Measure again"));
            });
        });
    }

    group
}

/// Benchmark the system resolvers plus a handful of well-known public ones.
fn run_dns_benchmark() -> Vec<network::DnsResult> {
    let mut candidates: Vec<Resolver> = Vec::new();
    for (i, address) in network::system_resolvers().into_iter().enumerate() {
        candidates.push(Resolver {
            name: format!("{} #{}", i18n("System"), i + 1),
            address,
        });
    }
    for (name, address) in PUBLIC_RESOLVERS {
        let Ok(address) = address.parse() else {
            continue;
        };
        if !candidates.iter().any(|c| c.address == address) {
            candidates.push(Resolver {
                name: (*name).to_owned(),
                address,
            });
        }
    }
    candidates
        .iter()
        .map(|r| network::benchmark_resolver(r, PROBE_DOMAINS, Duration::from_secs(2)))
        .collect()
}

fn status_icon(good: bool) -> gtk4::Image {
    let icon = gtk4::Image::from_icon_name(if good {
        "emblem-ok-symbolic"
    } else {
        "dialog-information-symbolic"
    });
    icon.add_css_class(if good { "success" } else { "dim-label" });
    icon
}

// ── Support report ──────────────────────────────────────────────────────────

fn report_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Support report"));
    group.set_description(Some(&i18n(
        "Everything a supporter needs about this machine. Your username, home \
         directory, hostname and public network addresses are removed as the \
         report is built.",
    )));

    let buffer = gtk4::TextBuffer::new(None);
    buffer.set_text(&i18n("Generating…"));

    let view = gtk4::TextView::builder()
        .buffer(&buffer)
        .editable(false)
        .monospace(true)
        .left_margin(12)
        .right_margin(12)
        .top_margin(12)
        .bottom_margin(12)
        .build();

    let scroll = gtk4::ScrolledWindow::builder()
        .child(&view)
        .height_request(320)
        .hscrollbar_policy(gtk4::PolicyType::Automatic)
        .build();
    scroll.add_css_class("card");

    let copy = gtk4::Button::builder().label(i18n("Copy")).build();
    let save = gtk4::Button::builder().label(i18n("Save to file…")).build();
    let refresh = gtk4::Button::builder()
        .icon_name("view-refresh-symbolic")
        .tooltip_text(i18n("Regenerate"))
        .build();

    let actions = gtk4::Box::new(gtk4::Orientation::Horizontal, 6);
    actions.set_halign(gtk4::Align::End);
    actions.set_margin_top(6);
    actions.append(&refresh);
    actions.append(&copy);
    actions.append(&save);

    let column = gtk4::Box::new(gtk4::Orientation::Vertical, 0);
    column.append(&scroll);
    column.append(&actions);
    group.add(&column);

    let generate = {
        let buffer = buffer.clone();
        move || {
            let buffer = buffer.clone();
            glib::spawn_future_local(async move {
                // Generating probes hardware, D-Bus and sysfs; it belongs off
                // the main thread even though it only takes a moment.
                let text = gio::spawn_blocking(|| bigame_core::diagnostics::report(false))
                    .await
                    .unwrap_or_else(|_| i18n("Could not generate the report."));
                buffer.set_text(&text);
            });
        }
    };
    generate();
    {
        let generate = generate.clone();
        refresh.connect_clicked(move |_| generate());
    }

    {
        let buffer = buffer.clone();
        copy.connect_clicked(move |button| {
            let text = buffer
                .text(&buffer.start_iter(), &buffer.end_iter(), false)
                .to_string();
            if let Some(display) = gtk4::gdk::Display::default() {
                display.clipboard().set_text(&text);
                toast::show(button, &i18n("Report copied"));
            }
        });
    }

    {
        let buffer = buffer.clone();
        save.connect_clicked(move |button| {
            let dialog = gtk4::FileDialog::builder()
                .title(i18n("Save diagnostics"))
                .initial_name("bigame-mode-diagnostics.txt")
                .build();
            let text = buffer
                .text(&buffer.start_iter(), &buffer.end_iter(), false)
                .to_string();
            let button = button.clone();
            let window = button.root().and_downcast::<gtk4::Window>();
            dialog.save(window.as_ref(), gio::Cancellable::NONE, move |result| {
                let Ok(file) = result else { return };
                let Some(path) = file.path() else { return };
                match std::fs::write(&path, text.as_bytes()) {
                    Ok(()) => toast::show(&button, &i18n("Report saved")),
                    Err(e) => toast::show(
                        &button,
                        &i18n("Could not save: %s").replace("%s", &e.to_string()),
                    ),
                }
            });
        });
    }

    group
}
