//! Diagnostics: one page to hand to support, and the network measurements.
//!
//! Two things live here because they answer the same question from different
//! angles — "what is this machine doing?" — and because both are read-only.
//! Nothing on this page changes the system.
//!
//! The report is generated by `bigame_core::diagnostics`, which strips personal
//! identifiers as it builds rather than filtering afterwards. The page never
//! sees an unredacted version, so there is nothing here that could leak one.

use std::fmt::Write as _;

use adw::prelude::*;
use gtk4::{gio, glib};
use libadwaita as adw;

use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;

use bigame_core::network::{self, Resolver};

use crate::i18n::i18n;
use crate::widgets::toast;

/// Resolvers offered for comparison, alongside whatever the system uses.
const PUBLIC_RESOLVERS: &[(&str, &str)] = &[
    ("Cloudflare", "1.1.1.1"),
    ("Google", "8.8.8.8"),
    ("Quad9", "9.9.9.9"),
    ("OpenDNS", "208.67.222.222"),
];

/// Domains queried by the DNS benchmark.
///
/// Distinct names on purpose: querying one repeatedly measures the resolver's
/// cache rather than the resolver, and a cold lookup is what a game launcher
/// actually performs.
const PROBE_DOMAINS: &[&str] = &[
    "steamcommunity.com",
    "store.steampowered.com",
    "epicgames.com",
    "gog.com",
    "ea.com",
    "ubisoft.com",
    "battle.net",
    "riotgames.com",
    "playstation.com",
    "xbox.com",
    "nvidia.com",
    "amd.com",
];

/// Build the Diagnostics page.
#[must_use]
pub fn build() -> gtk4::Widget {
    let page = adw::PreferencesPage::new();
    page.add(&health_group());
    page.add(&ai_graphics_group());
    page.add(&background_group());
    page.add(&steam_group());
    page.add(&network_group());
    page.add(&report_group());
    page.upcast()
}

// ── AI Graphics ─────────────────────────────────────────────────────────────

/// Games BiGame-mode placed graphics files in, each with what is happening
/// now — read from what the game loaded and `OptiScaler`'s own log — and a
/// way into its AI Graphics page (details, repair, restore, report).
fn ai_graphics_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("AI Graphics"));
    group.set_description(Some(&i18n(
        "Games BiGame-mode has installed upscaler files into. Open one for its details, to \
         repair it, to restore the game's own files, or to save a support report.",
    )));
    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    // Filled every time the page is shown: a game changed from its AI
    // Graphics page since the last visit must be here, with what it is
    // doing now.
    let fill = {
        let group = group.clone();
        let rows = rows.clone();
        move || {
            let group = group.clone();
            let rows = rows.clone();
            glib::spawn_future_local(async move {
                let found = gio::spawn_blocking(|| {
                    bigame_core::graphics::installed()
                        .into_iter()
                        .map(|t| {
                            let status = bigame_core::graphics::status(&t);
                            (t, status)
                        })
                        .collect::<Vec<_>>()
                })
                .await
                .unwrap_or_default();
                for r in rows.borrow_mut().drain(..) {
                    group.remove(&r);
                }
                if found.is_empty() {
                    let empty = adw::ActionRow::builder()
                        .title(i18n("None"))
                        .subtitle(i18n("AI Graphics has not changed any game"))
                        .use_markup(false)
                        .build();
                    group.add(&empty);
                    rows.borrow_mut().push(empty);
                    return;
                }
                for (target, status) in found {
                    let row = adw::ActionRow::builder()
                        .title(&target.name)
                        .subtitle(crate::views::ai_graphics::status_text(&status))
                        .use_markup(false)
                        .build();
                    let open = gtk4::Button::builder()
                        .icon_name("go-next-symbolic")
                        .valign(gtk4::Align::Center)
                        .tooltip_text(i18n("Open"))
                        .css_classes(["flat"])
                        .build();
                    let t = target.clone();
                    open.connect_clicked(move |b| {
                        crate::views::ai_graphics::open(b, t.clone(), None);
                    });
                    row.add_suffix(&open);
                    row.set_activatable_widget(Some(&open));
                    group.add(&row);
                    rows.borrow_mut().push(row);
                }
            });
        }
    };
    let on_map = fill.clone();
    group.connect_map(move |_| on_map());
    fill();
    group
}

// ── Background load ─────────────────────────────────────────────────────────

/// Is everything a game needs here, and does it work? Each row says what was
/// found and, when something is wrong, the command that fixes it — copied,
/// never run: a fix that needs root is the user's to run, and nothing here
/// deletes anything.
fn health_group() -> adw::PreferencesGroup {
    use bigame_core::health::Status;

    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("System health"));
    group.set_description(Some(&i18n(
        "What games need on this machine, and whether it works.",
    )));
    let copy_all = gtk4::Button::builder()
        .icon_name("edit-copy-symbolic")
        .tooltip_text(i18n("Copy all checks"))
        .css_classes(["flat"])
        .build();
    copy_all.update_property(&[gtk4::accessible::Property::Label(&i18n("Copy all checks"))]);
    group.set_header_suffix(Some(&copy_all));
    let placeholder = adw::ActionRow::builder().title(i18n("Checking…")).build();
    group.add(&placeholder);

    let group_ref = group.clone();
    glib::spawn_future_local(async move {
        let checks = gio::spawn_blocking(bigame_core::health::collect)
            .await
            .unwrap_or_default();
        group_ref.remove(&placeholder);
        let mut text = String::new();
        for c in &checks {
            let (icon, css) = match c.status {
                Status::Ok => ("object-select-symbolic", "success"),
                Status::Info => ("dialog-information-symbolic", "dim-label"),
                Status::Warning => ("dialog-warning-symbolic", "warning"),
                Status::Error => ("dialog-error-symbolic", "error"),
                Status::NotApplicable => ("action-unavailable-symbolic", "dim-label"),
            };
            let subtitle = match &c.fix {
                Some(fix) => format!("{}\n→ {}", c.detail, fix.text()),
                None => c.detail.clone(),
            };
            // Plain text: a fix like `sudo pacman -S … && sudo systemctl …`
            // is invalid Pango markup, and a row with markup on renders an
            // invalid subtitle as nothing at all.
            let row = adw::ActionRow::builder()
                .title(&c.title)
                .subtitle(&subtitle)
                .subtitle_lines(4)
                .use_markup(false)
                .build();
            let image = gtk4::Image::from_icon_name(icon);
            image.add_css_class(css);
            row.add_prefix(&image);
            if let Some(bigame_core::health::Fix::Command(command)) = &c.fix {
                let copy = gtk4::Button::builder()
                    .icon_name("edit-copy-symbolic")
                    .tooltip_text(i18n("Copy the command"))
                    .valign(gtk4::Align::Center)
                    .css_classes(["flat"])
                    .build();
                copy.update_property(&[gtk4::accessible::Property::Label(&i18n(
                    "Copy the command",
                ))]);
                let command = command.clone();
                copy.connect_clicked(move |b| {
                    b.clipboard().set_text(&command);
                    crate::widgets::toast::show(b, &i18n("Copied"));
                });
                row.add_suffix(&copy);
            }
            group_ref.add(&row);
            let _ = writeln!(
                text,
                "{:?}\t{}\t{}{}",
                c.status,
                c.title,
                c.detail,
                c.fix
                    .as_ref()
                    .map_or_else(String::new, |f| format!("\t→ {}", f.text()))
            );
        }
        copy_all.connect_clicked(move |b| {
            b.clipboard().set_text(&text);
            crate::widgets::toast::show(b, &i18n("Copied"));
        });
    });
    group
}

/// What else is using the CPU right now.
///
/// This lists and explains; it does not act. The mechanism for deprioritising
/// a process you own is easy — the hard part is being right about *which* one.
/// A compile left running deliberately, a video export someone is waiting on,
/// a browser playing the music they are listening to: each looks identical to
/// "background load" from `/proc`, and quietly slowing any of them down is a
/// worse outcome than a few lost frames.
///
/// So the user decides. Anything automatic here would have to be opt-in per
/// application and carry the same snapshot-and-restore discipline as every
/// other change this project makes.
fn background_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Background load"));
    group.set_description(Some(&i18n(
        "Programs of yours using noticeable CPU. Closing or pausing them frees \
         it for a game — but only you know which ones you are actually using.",
    )));

    let placeholder = adw::ActionRow::builder()
        .title(i18n("Measuring…"))
        .sensitive(false)
        .build();
    group.add(&placeholder);

    {
        let group = group.clone();
        let placeholder = placeholder.clone();
        glib::spawn_future_local(async move {
            // Sampling needs two readings a second or so apart — cumulative
            // CPU time from one reading says nothing about the present.
            let busy = gio::spawn_blocking(|| {
                bigame_core::processes::busy_processes(Duration::from_secs(2))
            })
            .await
            .unwrap_or_default();

            group.remove(&placeholder);
            if busy.is_empty() {
                let row = adw::ActionRow::builder()
                    .title(i18n("Nothing competing for the CPU"))
                    .subtitle(i18n("No program of yours is using a noticeable share."))
                    .build();
                row.add_prefix(&status_icon(true));
                group.add(&row);
                return;
            }

            for process in busy {
                let row = adw::ActionRow::builder()
                    .title(&process.name)
                    .subtitle(format!(
                        "{:.0}% {} · {} MiB · {}",
                        process.cpu_percent,
                        i18n("of one CPU"),
                        process.memory_mib,
                        process.kind.describe()
                    ))
                    .build();
                row.add_prefix(&gtk4::Image::from_icon_name(match process.kind {
                    bigame_core::processes::Kind::Browser => "web-browser-symbolic",
                    bigame_core::processes::Kind::Gaming => "applications-games-symbolic",
                    bigame_core::processes::Kind::Media => "video-x-generic-symbolic",
                    bigame_core::processes::Kind::Virtualisation => "computer-symbolic",
                    _ => "system-run-symbolic",
                }));
                group.add(&row);
            }
        });
    }

    group
}

// ── Steam launch options ────────────────────────────────────────────────────

/// Steam launch options that name a program which is not installed.
///
/// Steam runs the string through a shell, so a missing wrapper means the game
/// simply does not start — and nothing in Steam's interface explains it. This
/// machine had exactly that: an app carrying `gamemoderun %command%` with Feral
/// `GameMode` uninstalled.
///
/// Clearing the option is offered rather than done. It is the user's
/// configuration, and the alternative fix — installing the missing program — is
/// equally valid and not ours to choose.
fn steam_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Steam launch options"));
    group.set_description(Some(&i18n(
        "Options that call a program this system does not have. Steam runs them \
         through a shell, so the game will not start.",
    )));
    group.set_visible(false);

    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    let group_ref = group.clone();
    let rows_ref = Rc::clone(&rows);

    let refresh: Rc<dyn Fn()> = Rc::new(move || {
        for row in rows_ref.borrow_mut().drain(..) {
            group_ref.remove(&row);
        }
        let group = group_ref.clone();
        let rows = Rc::clone(&rows_ref);
        glib::spawn_future_local(async move {
            let broken = gio::spawn_blocking(scan_broken_launch_options)
                .await
                .unwrap_or_default();
            group.set_visible(!broken.is_empty());
            for entry in broken {
                let row = build_broken_row(&entry);
                group.add(&row);
                rows.borrow_mut().push(row);
            }
        });
    });
    refresh();
    // Re-scan after a fix so the row disappears instead of lingering.
    STEAM_REFRESH.with(|cell| *cell.borrow_mut() = Some(Rc::clone(&refresh)));

    group
}

thread_local! {
    /// Lets a fix handler ask the group to rebuild itself.
    static STEAM_REFRESH: RefCell<Option<Rc<dyn Fn()>>> = const { RefCell::new(None) };
}

/// One broken option, with enough context to describe it.
struct BrokenOption {
    config: std::path::PathBuf,
    app_id: String,
    title: String,
    missing: String,
    options: String,
}

fn scan_broken_launch_options() -> Vec<BrokenOption> {
    let Ok(home) = std::env::var("HOME") else {
        return Vec::new();
    };
    let home = std::path::PathBuf::from(home);
    let mut out = Vec::new();
    for user in bigame_core::steam::users(&home) {
        for broken in bigame_core::steam::broken_launch_options(&user.config) {
            out.push(BrokenOption {
                title: steam_app_name(&home, &broken.app_id),
                config: user.config.clone(),
                app_id: broken.app_id,
                missing: broken.missing,
                options: broken.options,
            });
        }
    }
    out
}

/// A game's title from its Steam manifest, or its `AppID` if it is not installed.
fn steam_app_name(home: &std::path::Path, app_id: &str) -> String {
    for root in bigame_core::games::steam_libraries(home) {
        let manifest = root.join(format!("steamapps/appmanifest_{app_id}.acf"));
        if let Ok(content) = std::fs::read_to_string(&manifest) {
            if let Some(name) = bigame_core::games::acf_value(&content, "name") {
                return name;
            }
        }
    }
    i18n("Steam app %s").replace("%s", app_id)
}

fn build_broken_row(entry: &BrokenOption) -> adw::ActionRow {
    let row = adw::ActionRow::builder()
        .title(&entry.title)
        .subtitle(
            i18n("Calls '%p', which is not installed — launch options: %o")
                .replace("%p", &entry.missing)
                .replace("%o", &entry.options),
        )
        .build();
    row.add_prefix(&{
        let icon = gtk4::Image::from_icon_name("dialog-warning-symbolic");
        icon.add_css_class("warning");
        icon
    });

    let clear = gtk4::Button::builder()
        .label(i18n("Clear launch options"))
        .valign(gtk4::Align::Center)
        .build();

    let config = entry.config.clone();
    let app_id = entry.app_id.clone();
    clear.connect_clicked(move |button| {
        // Steam holds this file in memory and rewrites it on exit, so an edit
        // made underneath a running client is silently discarded. Say so rather
        // than appearing to work.
        if bigame_core::steam::is_running() {
            toast::show(
                button,
                &i18n("Close Steam first — it would overwrite this change when it exits."),
            );
            return;
        }
        match bigame_core::steam::set_launch_options(&config, &app_id, "") {
            Ok(()) => {
                toast::show(button, &i18n("Launch options cleared"));
                STEAM_REFRESH.with(|cell| {
                    if let Some(refresh) = cell.borrow().as_ref() {
                        refresh();
                    }
                });
            }
            Err(e) => toast::show(
                button,
                &i18n("Could not change it: %s").replace("%s", &e.to_string()),
            ),
        }
    });
    row.add_suffix(&clear);
    row
}

// ── Network ─────────────────────────────────────────────────────────────────

/// Building a widget tree is inherently linear — splitting it yields helpers
/// with a single caller and no independent meaning — so the length lint is
/// allowed here rather than worked around.
#[allow(clippy::too_many_lines)]
fn network_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Network"));
    group.set_description(Some(&i18n(
        "Measured on the connection that carries your traffic, not on every \
         interface this machine happens to have.",
    )));

    let link_row = adw::ActionRow::builder()
        .title(i18n("Connection"))
        .subtitle(i18n("Checking…"))
        .build();
    group.add(&link_row);

    let qdisc_row = adw::ActionRow::builder()
        .title(i18n("Queue discipline"))
        .subtitle(i18n("Checking…"))
        .build();
    group.add(&qdisc_row);

    // Populated once, off the main thread; nothing here changes while the page
    // is open, so there is no reason to poll it.
    {
        let link_row = link_row.clone();
        let qdisc_row = qdisc_row.clone();
        glib::spawn_future_local(async move {
            let link = gio::spawn_blocking(network::primary_link)
                .await
                .ok()
                .flatten();
            if let Some(link) = link {
                link_row.set_title(&link.name);
                link_row.set_subtitle(&format!(
                    "{} · {} · MTU {}",
                    match link.medium {
                        network::Medium::Ethernet => i18n("Wired"),
                        network::Medium::WiFi => i18n("Wi-Fi"),
                        network::Medium::Virtual => i18n("Virtual"),
                        network::Medium::Unknown => i18n("Unknown"),
                    },
                    link.speed_mbps
                        .map_or_else(|| i18n("unknown speed"), |s| format!("{s} Mb/s")),
                    link.mtu.map_or_else(|| "?".to_owned(), |m| m.to_string())
                ));

                let modern = link.has_modern_qdisc();
                qdisc_row.set_subtitle(&format!(
                    "{} — {}",
                    link.qdisc.as_deref().unwrap_or(&i18n("unknown")),
                    if modern {
                        // Saying "already good" matters: offering to enable
                        // something that is on would be a no-op reported as
                        // an improvement.
                        i18n("already manages latency under load; nothing to change")
                    } else {
                        i18n("does not actively manage latency under load")
                    }
                ));
                qdisc_row.add_prefix(&status_icon(modern));
            } else {
                link_row.set_subtitle(&i18n("No default route — this machine is offline"));
                qdisc_row.set_visible(false);
            }
        });
    }

    // ── DNS benchmark ───────────────────────────────────────────────────
    let dns_group = adw::ExpanderRow::builder()
        .title(i18n("DNS resolver comparison"))
        .subtitle(i18n(
            "Measures how quickly each resolver answers a lookup. It does not \
             change the round-trip time of match traffic.",
        ))
        .build();

    let run_button = gtk4::Button::builder()
        .label(i18n("Measure"))
        .valign(gtk4::Align::Center)
        .css_classes(["suggested-action"])
        .build();
    dns_group.add_suffix(&run_button);
    group.add(&dns_group);

    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    {
        let dns_group = dns_group.clone();
        let rows = Rc::clone(&rows);
        let run_button = run_button.clone();
        run_button.clone().connect_clicked(move |_| {
            for row in rows.borrow_mut().drain(..) {
                dns_group.remove(&row);
            }
            run_button.set_sensitive(false);
            run_button.set_label(&i18n("Measuring…"));
            dns_group.set_expanded(true);

            let dns_group = dns_group.clone();
            let rows = Rc::clone(&rows);
            let run_button = run_button.clone();
            glib::spawn_future_local(async move {
                let results = gio::spawn_blocking(run_dns_benchmark)
                    .await
                    .unwrap_or_default();

                let fastest = network::fastest(&results).map(|r| r.resolver.name.clone());
                for result in &results {
                    let row = adw::ActionRow::builder()
                        .title(&result.resolver.name)
                        .build();
                    match &result.stats {
                        Some(stats) => {
                            row.set_subtitle(&format!(
                                "{} {:.1} ms · {} {:.1} ms · {} {:.1} ms",
                                i18n("median"),
                                stats.median_ms,
                                i18n("95th percentile"),
                                stats.p95_ms,
                                i18n("jitter"),
                                stats.jitter_ms
                            ));
                            if fastest.as_deref() == Some(result.resolver.name.as_str()) {
                                let badge = gtk4::Label::new(Some(&i18n("Fastest lookups")));
                                badge.add_css_class("caption");
                                badge.add_css_class("success");
                                badge.set_valign(gtk4::Align::Center);
                                row.add_suffix(&badge);
                            }
                        }
                        None => row.set_subtitle(&i18n("No response")),
                    }
                    dns_group.add_row(&row);
                    rows.borrow_mut().push(row);
                }

                // The disclaimer is part of the result, not a footnote: the
                // whole point is that a faster resolver is not a faster game.
                let note = adw::ActionRow::builder()
                    .title(i18n("What this does not mean"))
                    .subtitle(network::dns_disclaimer())
                    .build();
                note.add_prefix(&gtk4::Image::from_icon_name("dialog-information-symbolic"));
                dns_group.add_row(&note);
                rows.borrow_mut().push(note);

                run_button.set_sensitive(true);
                run_button.set_label(&i18n("Measure again"));
            });
        });
    }

    group
}

/// Benchmark the system resolvers plus a handful of well-known public ones.
fn run_dns_benchmark() -> Vec<network::DnsResult> {
    let mut candidates: Vec<Resolver> = Vec::new();
    for (i, address) in network::system_resolvers().into_iter().enumerate() {
        candidates.push(Resolver {
            name: format!("{} #{}", i18n("System"), i + 1),
            address,
        });
    }
    for (name, address) in PUBLIC_RESOLVERS {
        let Ok(address) = address.parse() else {
            continue;
        };
        if !candidates.iter().any(|c| c.address == address) {
            candidates.push(Resolver {
                name: (*name).to_owned(),
                address,
            });
        }
    }
    candidates
        .iter()
        .map(|r| network::benchmark_resolver(r, PROBE_DOMAINS, Duration::from_secs(2)))
        .collect()
}

fn status_icon(good: bool) -> gtk4::Image {
    let icon = gtk4::Image::from_icon_name(if good {
        "object-select-symbolic"
    } else {
        "dialog-information-symbolic"
    });
    icon.add_css_class(if good { "success" } else { "dim-label" });
    icon
}

// ── Support report ──────────────────────────────────────────────────────────

fn report_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Support report"));
    group.set_description(Some(&i18n(
        "Everything a supporter needs about this machine. Your username, home \
         directory, hostname and public network addresses are removed as the \
         report is built.",
    )));

    let buffer = gtk4::TextBuffer::new(None);
    buffer.set_text(&i18n("Generating…"));

    let view = gtk4::TextView::builder()
        .buffer(&buffer)
        .editable(false)
        .monospace(true)
        .left_margin(12)
        .right_margin(12)
        .top_margin(12)
        .bottom_margin(12)
        .build();

    let scroll = gtk4::ScrolledWindow::builder()
        .child(&view)
        .height_request(320)
        .hscrollbar_policy(gtk4::PolicyType::Automatic)
        .build();
    scroll.add_css_class("card");

    let copy = gtk4::Button::builder().label(i18n("Copy")).build();
    let save = gtk4::Button::builder().label(i18n("Save to file…")).build();
    let refresh = gtk4::Button::builder()
        .icon_name("view-refresh-symbolic")
        .tooltip_text(i18n("Regenerate"))
        .build();

    let actions = gtk4::Box::new(gtk4::Orientation::Horizontal, 6);
    actions.set_halign(gtk4::Align::End);
    actions.set_margin_top(6);
    actions.append(&refresh);
    actions.append(&copy);
    actions.append(&save);

    let column = gtk4::Box::new(gtk4::Orientation::Vertical, 0);
    column.append(&scroll);
    column.append(&actions);
    group.add(&column);

    let generate = {
        let buffer = buffer.clone();
        move || {
            let buffer = buffer.clone();
            glib::spawn_future_local(async move {
                // Generating probes hardware, D-Bus and sysfs; it belongs off
                // the main thread even though it only takes a moment.
                let text = gio::spawn_blocking(|| bigame_core::diagnostics::report(false))
                    .await
                    .unwrap_or_else(|_| i18n("Could not generate the report."));
                buffer.set_text(&text);
            });
        }
    };
    generate();
    {
        let generate = generate.clone();
        refresh.connect_clicked(move |_| generate());
    }

    {
        let buffer = buffer.clone();
        copy.connect_clicked(move |button| {
            let text = buffer
                .text(&buffer.start_iter(), &buffer.end_iter(), false)
                .to_string();
            if let Some(display) = gtk4::gdk::Display::default() {
                display.clipboard().set_text(&text);
                toast::show(button, &i18n("Report copied"));
            }
        });
    }

    {
        let buffer = buffer.clone();
        save.connect_clicked(move |button| {
            let dialog = gtk4::FileDialog::builder()
                .title(i18n("Save diagnostics"))
                .initial_name("bigame-mode-diagnostics.txt")
                .build();
            let text = buffer
                .text(&buffer.start_iter(), &buffer.end_iter(), false)
                .to_string();
            let button = button.clone();
            let window = button.root().and_downcast::<gtk4::Window>();
            dialog.save(window.as_ref(), gio::Cancellable::NONE, move |result| {
                let Ok(file) = result else { return };
                let Some(path) = file.path() else { return };
                match std::fs::write(&path, text.as_bytes()) {
                    Ok(()) => toast::show(&button, &i18n("Report saved")),
                    Err(e) => toast::show(
                        &button,
                        &i18n("Could not save: %s").replace("%s", &e.to_string()),
                    ),
                }
            });
        });
    }

    group
}
